<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="EasyRegPro event management software was designed by event planners. It has the scalability, convenience, and functionality that event planners love.">

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "SoftwareApplication",
	  "url" : "https://easyregpro.com/",
	  "name": "EasyRegPro Event Registration Software"
	}
	</script>
	<title>EasyRegPro Event Management Software</title>
	<?php
		$root = $_SERVER['DOCUMENT_ROOT'];
		include($root."/common_functions.php");
		include($root."/commonStyles.php");
		include($root."/commonJs.php");
	?>
	<link href="https://fonts.googleapis.com/css?family=Arbutus+Slab|Copse|Old+Standard+TT|Scheherazade|Suranna|Trocchi&display=swap" rel="stylesheet">
	<style>
		/*font-family: 'Old Standard TT', serif;
		font-family: 'Scheherazade', serif;
		font-family: 'Arbutus Slab', serif;
		font-family: 'Suranna', serif;
		font-family: 'Copse', serif;
		font-family: 'Trocchi', serif;*/
		.featuresTbl{
			float:left;
			width:45%;
			margin-left:2em;
		}
		.featuresTbl img{ display:block; }
		#easyRegLogo{
			background: rgb(51,93,101);
			background: radial-gradient(circle, #335d66 0%, #68a2a2 100%);
			color: white;
			/*-webkit-box-shadow: 10px 10px 29px 0px rgba(0,0,0,0.75);
			-moz-box-shadow: 10px 10px 29px 0px rgba(0,0,0,0.75);
			box-shadow: 10px 10px 29px 0px rgba(0,0,0,0.75);*/
			margin: 15px 0px 8em 0px;
			border-radius: 20px 20px 20px 20px;
			-moz-border-radius: 20px 20px 20px 20px;
			-webkit-border-radius: 20px 20px 20px 20px;
			border: 0px solid #000000;
			padding: 5px 0px 1em 0px;
		}
		#easyRegLogo H1{
			font-size: 42pt;
			margin-top: 0px;
			font-family: Times New Roman;
			text-shadow: 2px 2px 0px #408E75;
		}
		.featuresTbl{
			text-align: center;
			width:98%;
			margin:auto;
		}
		.featuresTbl img{
			display: block;
			margin: auto;
		}
		.featuresTbl H1{
			font-weight: bold;
			font-size: 26pt;
			color:#3d8585;
			text-shadow: 2px 2px 2px #baefc5;
		}
		.featuresTbl td{
			vertical-align: top;
			padding-left: 2em;
		}
		.featuresTbl td:first-child{
			padding-right:2em;
			padding-left:0em;
		}

		.featuresTbl img.divider{
			height: 25px;
			margin-top: 2em;
			margin-bottom: 2em;
		}
		#erpLogo{ margin-top: 3px; }
		#findEvent{
			border-radius: 3px 3px 3px 3px;
			-moz-border-radius: 3px 3px 3px 3px;
			-webkit-border-radius: 3px 3px 3px 3px;
			border: 1px solid #5b9a9a;
		}
		#findEvent{ padding-left: .5em; }
		#pageHeader, #pageHeader a{
			color:#5b9a9a;
			font-weight: bold;
			font-size:15pt;
		}
		#pageHeader input{
			font-weight: normal;
			font-size: 12pt;
			color:black;
		}
		body{ color:#335d65; }
		.imgDescription{
			font-family:Tahoma;
			font-size: medium;
			color:black;
			width:90%;
			margin:auto;
			text-align:left;
			margin-top:10px;
		}
		.imgDescription.center{
			text-align: center;
			margin-top: 0px;
		}
		.dialogRight .dialogTitle{ background-color: #2f93a5; }
		.dialogRight{ min-width:70%; }
		#contactDialog .table td{ border-top:none; }

		.survey-star{ font-size:23pt; cursor:pointer;	}
		.bi-star.survey-star{ color:#807a7a; }
		.bi-star.survey-star:hover, .bi-star-fill.survey-star{ color:#dbbc15; }
		.qLabel {
		    font-size: large;
		    font-weight: bold;
		    border-bottom: 1px solid black;
		    margin-top: 1em;
		    margin-bottom: 1em;
		}
	</style>
	<script type="text/javascript">
		let eventData = [];
		var app = angular.module('regApp', ['easyRegDataModule','erSvc', 'navMod']);
		app.controller('regController', function($scope, $http, $q, dataSvc, erSvc) {
			let searchHash = {};
			dataSvc.getArray({'query':'allEventSummary'}).then(function(resp){
				resp.forEach(function(evt){
					if(eventData.indexOf(evt.act) < 0) eventData.push(evt.act);
					let searchVal = evt.act + ': ' + evt.name + ' - ' + evt.city + ' ' + evt.state;
					eventData.push(searchVal);
					searchHash[searchVal] = `/e/${evt.eventSlug}`;
					if(!searchHash[evt.act]) searchHash[evt.act] = `/${evt.accountSlug}`;
				});
			});

			$('#findEvent').autocomplete({
				source: eventData,
				select: function(event, opt){
					window.location.href = searchHash[opt.item.label];
				},
				minLength:2
			});

			$scope.contact = function(type){
				$scope.requestType = type;
				$('#contactDialog').show(500);
				$scope.contactTitle = type == 'Information' ? 'Request Information' : 'Request a Demo';
			};

			$scope.closeRightDialog = function(){
				$('.dialogRight').hide(500);
			};

			$scope.sendRequest = function(){
				$('form[name="contactForm"]').addClass('submitted');
				if($scope.contactForm.$valid){
					let subject = `EasyRegPro ${$scope.requestType} Request`;
					let body = `Request sent by ${$scope.reqName} - ${$scope.reqCompany}<br/>`;
					body += `Return email - ${$scope.reqEmail}<br/><br/>`;
					body += $scope.reqBody;
					erSvc.sendEmail('info@psugevents.com', subject, body).then(function(res){
						$('form[name="contactForm"]').removeClass('submitted');
						$scope.reqBody = '';
						$scope.closeRightDialog();
						let msg = "Thank you for expressing interest in EasyRegPro.com.  Your request has been delivered.  You will hear back from us shortly.  If you need to amend your request, please send a message to info@psugevents.com.com.";
						erSvc.easyRegAlert({"text":msg,"title":"Thank You for Your Interest"});
					});
				}
			};

			var getRecs = dataSvc.getTableRecords;
			var questionsRetrieved = $q.defer();
			var evtQuestionsRetrieved = $q.defer();

			getRecs("survey_questions", "accountid = 1000", true).then(function(res){
				$scope.questions = res;
				questionsRetrieved.resolve();
			});

			$scope.getStarClass = function(val, question){
				let retClass = "bi bi-star survey-star";
				if(val <= question.response) retClass = "bi bi-star-fill survey-star";
				return retClass;
			};

		});// End Controller
	</script>
</head>

<body style="padding-top:1px" ng-app="regApp" ng-controller="regController">

	<div style="width:98%;display:flex;justify-content: center;align-items:center" id="pageHeader">
		
			<div style="padding-left:2em;width:32%">
				<img src="/img/ERP-no-tag.png" height="150" id="erpLogo">
			</div>
			<!-- <div style="text-align: center;flex-grow: 1;">
				<a class="btn btn-primary" href="/freeTrial.php" style="background:teal;color:white">
					Try for Free
				</a>
			</div> -->
			<div style="text-align:right;padding-right:3em;align-self:flex-start;padding-top:1em;width:32%">
				<b style="color:grey">Find Your Event</b><br/>
				<a href="/psugevents">PSUG Events</a><br/>
				<a href="/mba">MBA Events</a>
				<!-- <input id="findEvent" type='text'  style="margin-bottom:2em"/>
				<a href="#" ng-click="contact('Information')" style="margin-left:4em">Info</a>
				<a href="#" ng-click="contact('Demo')" style="margin-left:4em">Demo</a>
				<br/>
				<a href="#" ng-click="launchFirstFree()">Get Your First Event Free</a> -->
			</div>
		
	</div>

    <div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div id="easyRegLogo" class='center'>
					<H1 id="pgHeader">Dynamic Event Management Software</H1>
					<div style="font-size:15pt">
						<span style="font-family: 'Old Standard TT', serif;">EasyRegPro <sup>&copy;</sup></span>
						event management software was designed by event planners.<br/>
						It has the scalability, convenience, and functionality that event planners love.
					</div>
				</div>

				<table class="featuresTbl">
					<tr>
						<td style="width:50%"><H1>Centralized Event Management</H1></td>
						<td><H1>Seamless Brand Integration</H1></td>
					</tr>
					<tr>
						<td>
							<img src="/img/event-pg.png" style="width:90%">
							<div class="imgDescription" style="margin-top:18px">
								Keep all your events in one location with quick links to  the event home page. Show  upcoming events as well as  past events.  You determine what shows and when.
							</div>
						</td>
						<td>

							<img src="/img/brand-pg.png" style="width:90%">
							<div class="imgDescription">
								From the centralized landing page, to the event website, to the event program, your brand will carry through.
							</div>
						</td>
					</tr>
					<tr>
						<td colspan="2" class="center"><img class="divider" src="/img/divider.png"></td>
					</tr>
					<tr>
						<td><H1>Robust Scheduling Tool</H1></td>
						<td><H1>Dynamic Attendee Management</H1></td>
					</tr>
					<tr>
						<td>
							<img src="/img/Sched-pg.png" style="width:90%">
							<div class="imgDescription">
								Unlike any other scheduler on the market.Create the rooms and sessions needed to run a multi-day training event. Then use the wysiwyg schedule grid to add the courses and presenters in each time-slot.
							</div>
						</td>
						<td>
							<img src="/img/Att-pg.png" style="width:90%">
							<div class="imgDescription" style="margin-top:18px">
								See everyone scheduled to attend the event in one location.Filter by attendees with a balance, attendees from the same company, attendees from the same state or any combination of fields. Enter payments, send invoices, communicate via email. Manage all attendee information from a single page.
							</div>
						</td>
					</tr>
					<tr>
						<td colspan="2" class="center"><img class="divider" src="/img/divider.png"></td>
					</tr>
					<tr>
						<td><H1>Expedited On-site Check-In</H1></td>
						<td><H1>Customizable Event Website</H1></td>
					</tr>
					<tr>
						<td>
							<div class="imgDescription center">Badge Scanning or Manual Process</div>
							<img src="/img/check-in.png" style="width:90%">
							<div class="imgDescription">
								Expedite the check-in process by using badge scanning capability or search for attendees by hand. Attendees with a balance will be flagged.
							</div>
						</td>
						<td>
							<img src="/img/web-pg.png" style="width:90%">
							<div class="imgDescription">
								Use the built in Website page editor to add as many customized pages as needed. Provide attendees with hotel information, directions,things to-do in the area, whatever your event needs to be successful.
							</div>
						</td>
					</tr>
				</table>
			</div> <!-- End column -->
		</div> <!-- End row -->
	</div>

	<div id="contactDialog" class="dialogRight">
		<div class="dialogTitle">{{contactTitle}}</div>
		<div class="dialogContents">
			<form name="contactForm">
				<table class="table">
					<tr>
						<td class="bold" style="width:10em">Your Email</td>
						<td>
							<input ng-required="true" type="email" class="form-control" ng-model="reqEmail">
						</td>
					</tr>
					<tr>
						<td class="bold">Your Name</td>
						<td>
							<input ng-required="true" type="text" class="form-control" ng-model="reqName">
						</td>
					</tr>
					<tr>
						<td class="bold">Company Name</td>
						<td>
							<input ng-required="true" type="text" class="form-control" ng-model="reqCompany">
						</td>
					</tr>
					<tr>
						<td class="bold">Please Tell Us About Your Event(s) and Your Needs</td>
						<td>
							<textarea ng-required="true" class="form-control" ng-model="reqBody" rows="15"></textarea>
						</td>
					</tr>
				</table>
			</form>
			<div class="button-row">
				<button class="btn btn-primary" ng-click="closeRightDialog()">
					<span class="bi bi-chevron-left"></span> Cancel
				</button>
				<button class="btn btn-success" ng-click="sendRequest()">
					<span class="bi bi-check-lg"></span> Send Request
				</button>
			</div>
		</div>
	</div> <!-- End Contact Dialog -->

	<!-- <div id="firstFreeDialog" class="dialogRight">
		<div class="dialogTitle">Get Your First Event Free</div>
		<div class="dialogContents">
			<form>

				<div ng-repeat="question in surveyQuestions | orderObjectBy:'sortorder'">
					<div class="questionText {{question.type=='label'? 'qLabel' : ''}}">{{question.text}}</div>
					<div style="padding-left:2em">
						<div ng-show="question.type == 'numeric'">
							<span ng-repeat="val in [1,2,3,4,5]">
								<span ng-class="getStarClass(val, question)"
									ng-click="question.response = val"></span>
							</span>
						</div>
						<textarea ng-if="question.type == 'freeForm'" rows="8" cols="100" class="form-control"
							ng-model="question.response" style="width:70%"></textarea>
						<div ng-show="question.type == 'yesNo'" style="font-size:15pt">
							<label><input type="radio" value="yes" ng-model="question.response" /> Yes</label>
							<label><input type="radio" value="no" ng-model="question.response" style="margin-left:2em" /> No</label>
						</div>
						<div ng-show="question.type == 'multipleChoice'">
							<select
								style="width:90%"
								class="form-select"
								ng-options="q for q in question.optionList"
								ng-model="question.response">
							</select>
						</div>
					</div>
				</div>

			</form>
			<div class="button-row">
				<button class="btn btn-primary" ng-click="closeRightDialog()">
					<span class="bi bi-chevron-left"></span> Cancel
				</button>
				<button class="btn btn-success" ng-click="sendFirstFree()">
					<span class="bi bi-check-lg"></span> Submit
				</button>
			</div>
		</div>
	</div> <!-- End First Free Dialog --> -->

	<er-Footer />
</body>
</html>
