<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<?php include($_SERVER['DOCUMENT_ROOT']."/about/includes/headerContent.php"); ?>
	<meta name="description" content="The Event Phoenix event management software was designed by event planners. It has the scalability, convenience, and functionality that event planners love.">
	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
		{
		  "@context" : "http://schema.org",
		  "@type" : "SoftwareApplication",
		  "url" : "https://easyregpro.com/",
		  "name": "The Event Phoenix Event Registration Software"
		}
	</script>
</head>
<body>
	<?php include($root."/about/includes/nav.html"); ?>
	<section class="darkGreen" style="padding-top:4em">
		<H1 class="center" style="margin-top:0px;font-size:40pt;font-weight:bold">The Event Phoenix</H1>
		<section class="threeCol bold">
			<div style="padding-left: 3em;">
				<h2>Event Management & Ticketing</h2>
				<p> 
					The Event Phoenix is your one stop shop for events of any type. Conferences, conventions, 
					meetings and more.  Live, Virtual or Hybrid events! Meeting planners love The Event Phoenix!
				</p>
				<p>
					Our friends in the K12 market also love us. Used for Ticketing for sports and activities
					as well as Community Ed, Adult Ed,  Drivers Ed and more.
				</p>
				<p style="margin-top:1em" class="center">
					<a href="contact.php" class="button">Contact Us</a>
				</p>
			</div>
			<div class="center">
				<span style="min-height: 60px;display: block">
					<video width="400" autoplay muted loop>
					  <source src="img/conf2.mp4" type="video/mp4">
					</video>
				</span>
				<span style="font-size:13pt;font-style:italic;">Event Management Made Easy!</span>
			</div>
			<div class="center">
				<i style="display: block;">Designed "BY" Event Planners<br/>"FOR" Event Planners!</i>
				<a href="/freeTrial.php" class="button">Get The App</a>
				<img src="img/Handheld Mobile phone.webp" />
			</div>
		</section>
	</section>
	<section class="lightGreen" style="padding-bottom: 2em;">
		<div class="center">
			<h2 style="margin-top: 0px;">The Event Phoenix</h2>
			<p>
				Get The Event Phoenix and find out why others LOVE us!  You'll be a long term partner <br/>
				of ours and help us shape the future of event technology!
			</p>
		</div>
		<section class="threeCol">
			<div class="center">
				<img src="img/Keyboard.webp" class="round" />
				<H2>Live,In-Person Events</H2>
				<ul class="featureList">
					<li>Be Up & Running In Minutes!</li>
					<li>Live, In-Person Events</li>
					<li>Virtual Events</li>
					<li>Hybrid Events</li>
					<li>Mobile App-Fully Integrated</li>
					<li>Corporate Events</li>
					<li>Association Events</li>
					<li>K12 Programs, Sports & Activities</li>
					<li>Ticket Sales</li>
					<li>Easy Check In and Name Badges</li>
					<li>Branding and Sponsorships</li>
					<li>Ability to add Maps and Vendor Locations</li>
				</ul>
			</div>
			<div class="center">
				<img src="img/Tablet.webp" class="round" />
				<H2>Virtual & Hybrid Events</H2>
				<ul class="featureList">
					<li>Staff Management</li>
					<li>Vendor Management</li>
					<li>Video Management</li>
					<li>Document Management</li>
					<li>Expense Management</li>
					<li>Unlimited Topic Tracks </li>
					<li>Inventory Management</li>
					<li>Course Management</li>
					<li>Drag & Drop Schedule</li>
					<li>Ticket Sales</li>
					<li>Easy Check In and Name Badges</li>
					<li>Branding and Sponsorships</li>
				</ul>
			</div>
			<div class="center">
				<img src="img/Mobile.webp" class="round" />
				<H2>Mobile App</H2>
				<ul class="featureList">
					<li>Fully Customizable Event Pages</li>
					<li>Unlimited Custom Event Pages</li>
					<li>Customizable Fields</li>
					<li>Analytics</li>
					<li>Social Integration/ Gamification</li>
					<li>Ticket Sales</li>
					<li>Attendees Build Schedule Live</li>
					<li>Session & Overall Surveys</li>
					<li>Multiple Credit Card Partners</li>
					<li>Lead Generation for Vendors</li>
					<li>Easy Check In and Name Badges</li>
					<li>Branding and Sponsorships</li>
					<li>In-App Attendee Networking</li>
					<li>Attendee Engagement Through Polls, Surveys, and Push Notifications</li>
				</ul>
			</div>
		</section>
		<br/>
		<br/>
		<p class='center'>
			<a class="button" href="/freeTrial.php">Try The Event Phoenix for FREE!</a>
		</p>
	</section>
	<section style="display: flex; flex-wrap: wrap;">
		<div style="width:25%;padding-right:1em;font-size:3em;color:gray" class="right"> 
			<span class="material-icons">insights</span>
		</div>
		<div style="width:25%;">
			<p style="color:#20bc91">THE ONLY APP YOU'LL EVER NEED</p>
			<p>
				Our founders have over 40 years of combined event management experience and designed 
				The Event Phoenix from scratch to do what every event planner wants and needs!  
				Try it now for FREE*!!
			</p>
		</div>
		<div style="width:2em;font-size:3em;color:gray;padding-right:1em" class="right">
				<span class="material-icons">workspace_premium</span>
		</div>
		<div style="width:25%;">
			<p style="color:#20bc91">MAKE THE CHANGE</p>
			<p>
				Be a part of our ever growing The Event Phoenix family!  
				Click on the GET THE APP button to get started.  You'll find the best and 
				easiest to use app out there!
			</p>
		</div>
	</section>
	<section class="threeCol">
		<div>
			<a href="features.php"><img src="img/evt.jpg" style="width:100%;height:350px" /></a>
			<p class="center lightGreen"><a href="features.php" class="featureLink">Event Management</a></p>
		</div>
		<div>
			<a href="app.php"><img src="img/tablet.jpg" style="width:100%;height:350px" /></a>
			<p class="center lightGreen"><a href="app.php" class="featureLink">Mobile App</a></p>
		</div>
		<div>
			<a href="k12.php"><img src="img/K12 Page.jpg" style="width:100%;height:350px" /></a>
			<p class="center lightGreen"><a href="k12.php" class="featureLink">K12 Education</a></p>
		</div>
	</section>
	<section class="darkGreen" style="padding-bottom: 2em;">
		<div style="width:30em;margin:auto">
			<H1 class="center">FIRST EVENT FREE *</H1>
			<p>
				Help us celebrate the launch of our NEW
				The Event Phoenix Mobile App.  We are giving away
				our Amazing The Event Phoenix Event Management
				System (including our new mobile app) to the
				fist 50 users* for FREE for your first event!
			</p>
			<p style="font-size: 9pt;">
				*One time fee applies!  After your fist event, normal pricing begins.
			<p>
		</div>
	</section>
	<?php include($root."/about/includes/footer.html"); ?>
</body>
</html>